const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {JSDOM}=require('jsdom');
const d=new JSDOM('<button id="origin">Abrir</button>',{runScripts:'outside-only'}),w=d.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
w.eval(fs.readFileSync(path.join(__dirname,'../js/dungeon-delta-demo.js'),'utf8'));
w.document.getElementById('origin').focus();w.DungeonDeltaDemo.abrir();
const click=s=>w.document.querySelector(s).click();
assert.equal(w.document.querySelectorAll('.dd-card').length,6);
click('[data-id="2"][data-action="progress"]');click('[data-id="2"][data-action="progress"]');
assert.equal(w.document.querySelector('[data-card="2"]').dataset.state,'done');
click('[data-id="3"][data-action="start"]');click('[data-id="3"][data-action="pause"]');
assert.equal(w.document.querySelector('[data-card="3"]').dataset.state,'paused');
click('[data-forward]');assert.equal(w.document.querySelector('[data-card="4"]').dataset.state,'running');
assert.equal(w.document.querySelectorAll('.dd-card').length,7);
click('[data-id="4"][data-action="done"]');assert.match(w.document.querySelector('[data-card="4"]').textContent,/Sequência 3/);
click('[data-forward]');click('[data-forward]');
assert.equal(w.document.querySelector('[data-card="1"]').dataset.state,'ready');
assert.equal(w.document.querySelector('[data-card="7"]').dataset.state,'running');
click('[data-forward]');click('[data-forward]');
assert.equal(w.document.querySelector('[data-card="7"]').dataset.state,'failed');
assert.equal(w.document.querySelector('[data-card="4"]').dataset.state,'done');
click('[data-reset]');assert.equal(w.document.querySelectorAll('.dd-card').length,6);
click('[data-close]');assert.equal(w.document.querySelector('#delta-demo'),null);
assert.equal(w.document.activeElement.id,'origin');
console.log('OK: meta, pausa, horário, nova ocorrência, streak, expiração, histórico, reset e fechamento.');d.window.close();
