const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<div id="dg-col-ativas"></div><div id="dg-col-passivas"></div>',{runScripts:'outside-only'});
const w=dom.window;w.SoloDialog={toast(){}};
w.eval(fs.readFileSync(path.join(__dirname,'../js/pages/dungeon-interior.js'),'utf8')+';window.D=DungeonInterior');
const D=w.D;D._dungeon={};D._atualizarProjecao=()=>{};
const agora=Date.now(),futuro=new Date(agora+60000).toISOString();
D._sessao={id:1,status:'ATIVA',data:'2026-09-22',entrada_em:new Date(agora).toISOString(),agora_server:new Date(agora).toISOString(),agenda:[{missao:{id:2,titulo:'Água <script>',natureza:'BEM_ESTAR'},proxima_em:futuro}]};
D._execs=[{id:3,dungeon_missao_id:2,status:'EXPIRADA',disparada_em:new Date(agora-600000).toISOString(),streak:0,missao:{id:2,titulo:'Água',natureza:'BEM_ESTAR'}},{id:4,dungeon_missao_id:2,status:'CONCLUIDA',streak:1,missao:{id:2,titulo:'Água',natureza:'BEM_ESTAR'}}];
D._renderMissoes();D._tickUI();
assert.equal(w.document.querySelectorAll('[data-dg-card]').length,2);
assert.match(w.document.body.textContent,/Falhou/);assert.match(w.document.body.textContent,/Concluída/);
assert.match(w.document.querySelector('.dg-contagem').textContent,/00:01:00|00:00:59/);
assert.equal(w.document.querySelector('script'),null);
assert.match(D._agendaHTML(),/Água &lt;script&gt;/);
const scheduled={id:5,status:'PENDENTE',missao:{id:8,titulo:'Futura',natureza:'AGENDADA',hora_inicio:'23:59',xp_recompensa:30}};
D._timeOffset=Date.now()-D._instante('2026-09-22T12:00:00');
assert.match(D._mcardHTML(scheduled,0),/Abre em/);assert.doesNotMatch(D._mcardHTML(scheduled,0),/data-dg-acao="iniciar"/);
D._timeOffset=Date.now()-D._instante('2026-09-23T00:00:00');
assert.match(D._mcardHTML(scheduled,0),/data-dg-acao="iniciar"/);
assert.equal(D._instante('2026-09-22T12:00:00'),Date.parse('2026-09-22T15:00:00Z'));
console.log('OK: cards futuros, cronômetro, histórico, streak, escape de texto e abertura no horário.');dom.window.close();
